### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by geekdave** [TestArmada/crows-nest#1]
![crows-nest](https://cloud.githubusercontent.com/assets/1438478/18613191/055e771a-7d32-11e6-8f1c-9fe3c328696c.jpeg)

**Comment by ThaiWood** [comment]
Per [source Freshwater and Marine Image Bank from the University of Washington Libraries](http://digitalcollections.lib.washington.edu/cdm/singleitem/collection/fishimages/id/46545/rec/2), this image carries no copyright and is in the public domain.
