### ISSUE TITLE
Docker container for crows-nest

### ISSUE THREAD

**Issue by smccarthy** [TestArmada/crows-nest#18]
Is there a docker container for crows-nest ? My company is looking to run this in a container.

**Comment by geekdave** [comment]
@smccarthy Great idea... we are looking into it.

**Comment by smccarthy** [comment]
Btw, you mentioned a slack server for TestArmada, but I wasn't able to DM @TestArmada on twitter. Maybe you need to follow me, @shawnmccarthy0 ?

**Comment by geekdave** [comment]
@smccarthy Sent you a DM on the twitters

**Comment by ThaiWood** [comment]
@smccarthy we recently added a Dockerfile in #22 , sorry for the delay in updating this issue
