### ISSUE TITLE
Telegraf - Error: splitting '|', Unable to parse metric

### ISSUE THREAD

**Issue by IsReal8a** [TestArmada/crows-nest#41]
Hi team,
We're trying to get metrics into Telegraf and send those to a different places, however, seems like Telegraf doesn't like the formatting of the statds crow-nest output or something else is happening.
I enabled the statsd input plugin with the following configuration (on the same server):

> [[inputs.statsd]]
>   protocol = "udp"
>   max_tcp_connections = 250
>   service_address = ":8125"
>   delete_gauges = true
>   delete_counters = true
>   delete_sets = true
>   delete_timings = true
>   metric_separator = "."
>   allowed_pending_messages = 10000

Stats configuration on crow-nest's config.json

>  "stats": {
>     "statsType": "telegraf",
>     "statsPrefix": "",
>     "statsDatabase": "",
>     "statsHost":"localhost",
>     "statsPort":"8125"
>   },

Error message
`Mar 22 16:35:02 localhost telegraf: 2018-03-22T15:35:02Z I! Statsd UDP listener listening on:  [::]:8125
Mar 22 16:35:06 localhost telegraf: 2018-03-22T15:35:06Z E! Error: parsing sample rate, , it must be in format like: @0.1, @0.5, etc. Ignoring sample rate for line: status:1|g|#hostname:localhost,tunnelNum:1
Mar 22 16:35:06 localhost telegraf: 2018-03-22T15:35:06Z E! Error: splitting '|', Unable to parse metric: status:1|g|#localhost,tunnelNum:1
Mar 22 16:35:06 localhost telegraf: 2018-03-22T15:35:06Z E! Error: parsing sample rate, , it must be in format like: @0.1, @0.5, etc. Ignoring sample rate for line: age:3070297|g|#hostname:localhost,tunnelNum:1
Mar 22 16:35:06 localhost telegraf: 2018-03-22T15:35:06Z E! Error: splitting '|', Unable to parse metric: age:3070297|g|#hostname:localhost,tunnelNum:1`

I did some researching about Telegraf having these issues and I found something similar:
https://github.com/influxdata/telegraf/issues/3508
https://github.com/influxdata/telegraf/pull/3514
It wont be fixed on Telegraf though.

Now, I tested this format from the shell and it works:
`echo "age:1730173|g" | nc -u -w1 localhost 8125`

I don't need more information because I'm using the global tags from Telegraf.
Please help me checking if this isn't an issue on crow-nest or its something with the configuration, btw, good work and thank you.

**Comment by archlichking** [comment]
💯 🥇
